title: Developer{ish}
author: GitHub User
email: wrmyeresanara@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I am a fullstack developer in training from Lagos Nigeria
theme: minima

# social links
twitter_username: waieresanara # DO NOT include the @ character, or else the build will fail!
github_username:  warami13 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


